name: Build

on:
  release:
    types: [ published ] # when a release is created, build and publish bins
  #push:
  #  branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ] # when a pull request is opened only build

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  MODULE: thinger_monitor
  BUILD_TYPE: Release
  OPENSSL_ROOT_DIR: /usr/lib/ssl

jobs:

  build_version:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get tag version
      id : version
#      run: | # official regex for semantic version: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
#        echo "build_version=`grep -oE '(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?' run.sh | head -1`" >> $GITHUB_ENV
      #run: echo "build_version=`sed -n 's/.*BUILD_VERSION=//p' run.sh | cut -d " " -f1`" >> $GITHUB_ENV
#      run: echo "::set-output name=version::`sed -n 's/.*BUILD_VERSION=//p' run.sh | cut -d " " -f1`"
      run: |
        echo "::set-output name=version::$(echo ${GITHUB_REF}"

  build:
    runs-on: ubuntu-latest
    needs: build_version
    strategy:
      matrix:
        architecture: ["x86_64", "armv7m_eabi"]
    container:
      image: bautisflow/toolchains:musl_ssl_${{ matrix.architecture }}

    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ steps.extract_branch.outputs.branch }}

    - name: Configure CMake
      run: cmake -B /build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_VERSION=${{ needs.build_version.outputs.version }} -DCROSS=ON -DOPENSSL_ROOT_DIR=${{ env.OPENSSL_ROOT_DIR }} -DOPENSSL_LIBRARIES=${{ env.OPENSSL_ROOT_DIR }} -DBIN_EXTENSION=${{ matrix.architecture }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build /build --config ${{ env.BUILD_TYPE }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      if: ${{ github.event_name == 'release' }}
      with:
        name: ${{ env.MODULE }}.${{ matrix.architecture }}
        path: /build/${{ env.MODULE }}.${{ matrix.architecture }}
        if-no-files-found: error
        retention-days: 1

  # TODO: Install and run

  upload_to_release: # when tag is created
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: [build_version, build]
    strategy:
      matrix:
        architecture: ["x86_64", "armv7m_eabi"]

    steps:

    - name: Download ${{ matrix.architecture }} binary
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.MODULE }}.${{ matrix.architecture }}

    - name: Check file existence
      run: |
        echo ". directory"
        pwd
        ls -la .
        echo "github workspace directory"
        ls -la ${{ github.workspace }}

    - name: Upload x86_64 binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.MODULE }}.${{ matrix.architecture }}
        tag: ${{ needs.build_version.outputs.version }}

